In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('data.csv')
df=pd.DataFrame(data)
df.head()

Height  Weight
0    1.47   52.21
1    1.50   53.12
2    1.52   54.48
3    1.55   55.84
4    1.57   57.20

In [4]:
df.columns

Index(['Height', 'Weight'], dtype='object')

In [6]:
len(df)

15

In [7]:
len(df.columns)

2

In [49]:
df.isnull().sum()

Height    0
Weight    0
dtype: int64

In [9]:
df.describe()

Height     Weight
count  15.000000  15.000000
mean    1.650667  62.078000
std     0.114235   7.037515
min     1.470000  52.210000
25%     1.560000  56.520000
50%     1.650000  61.290000
75%     1.740000  67.190000
max     1.830000  74.460000

In [10]:
df.describe #what is this???

<bound method NDFrame.describe of     Height  Weight
0     1.47   52.21
1     1.50   53.12
2     1.52   54.48
3     1.55   55.84
4     1.57   57.20
5     1.60   58.57
6     1.63   59.93
7     1.65   61.29
8     1.68   63.11
9     1.70   64.47
10    1.73   66.28
11    1.75   68.10
12    1.78   69.92
13    1.80   72.19
14    1.83   74.46>

In [11]:
df.head()

Height  Weight
0    1.47   52.21
1    1.50   53.12
2    1.52   54.48
3    1.55   55.84
4    1.57   57.20

In [12]:
X=df['Height']
Y=df['Weight']  # Y=df.drop('Height')


In [34]:
X=X.values.reshape(-1,1)

In [51]:
print(X_train)

[[1.6 ]
 [1.68]
 [1.52]
 [1.5 ]
 [1.83]
 [1.57]
 [1.65]
 [1.73]
 [1.78]
 [1.55]
 [1.63]]


In [52]:
X_train.ndim

2

In [38]:
Y.sample(5)

13    72.19
11    68.10
1     53.12
6     59.93
12    69.92
Name: Weight, dtype: float64

In [39]:
import sklearn

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train,X_test,Y_train,Y_test=train_test_split(X, Y, test_size=0.22, random_state=42)

In [43]:
Y_train.sample(3)

14    74.46
6     59.93
7     61.29
Name: Weight, dtype: float64

In [44]:
X_test

array([[1.7 ],
       [1.75],
       [1.47],
       [1.8 ]])

In [45]:
Y_test

9     64.47
11    68.10
0     52.21
13    72.19
Name: Weight, dtype: float64

In [53]:
len(X_train) , len(Y_train)

(11, 11)

In [55]:
len(X_test) , len(Y_test)

(4, 4)

In [56]:
from sklearn.linear_model import LinearRegression

In [58]:
reg=LinearRegression()

In [59]:
reg.fit(X_train,Y_train) #X,Y sent to formula (y=mx+c)

LinearRegression()

In [61]:
reg.coef_

array([62.10683012])

In [63]:
reg.intercept_

-40.56429231014168

In [75]:
Y_predict=reg.predict(X_train)

In [76]:
Y_predict[:5]

array([58.80663589, 63.7751823 , 53.83808948, 52.59595287, 73.09120681])

# TRAINING

In [78]:
from sklearn.metrics import r2_score 

In [80]:
r2_score(Y_train,Y_predict)*100

99.00144543088145

# TEST

In [82]:
Y_test_pred=reg.predict(X_test)

In [83]:
Y_test_pred[:3]

array([65.0173189 , 68.1226604 , 50.73274797])

In [84]:
r2_score(Y_test_pred,Y_test)

0.9861524537037374

In [87]:
reg.predict([[7.0]])

array([394.18351855])